{"api": "PrintWriter.write", "prompt": "Please answer my code questions using the given API following this format: <<<api>>>: $API\n<<<code>>>: $CODE\n<<<explanation>>>: $EXPLANATION.\nQuestion: Why do I keep getting the \"must be caught or declared to be thrown\" error?: :                                This question is unlikely to help any future visitors; it is only relevant to a small geographic area, a specific moment in time,  or an extraordinarily narrow situation that is not generally applicable to the worldwide audience of the internet. For help making  this question more broadly applicable, visit the help center.                                                            Closed 11 years ago.Here is my codeimport java.io.*;import java.util.*;import java.util.Scanner;import java.io.PrintWriter;public class EncryptionDecryption {public static void main(String[] args) throws java.io.IOException{int z = getRandom();boolean luck = true;while(luck == true){String codeString = getString();System.out.println(codeString);char[] enCharArray = encrypt(codeString, z);String encryptedString = new String(enCharArray);System.out.println(encryptedString);char[] deCharArray = decrypt(encryptedString, z);String decryptedString = new String(deCharArray);System.out.println(decryptedString);putString(encryptedString);if(codeString.length() == 0)luck = false;}}static String getString(){Scanner input = new Scanner(new File(\" \"));String codeString = input.next();return codeString;}static void putString (String finalString){PrintWriter work = new PrintWriter(\"EncryptedDocument.txt\");work.print(finalString + \" \");work.close();}static char[] encrypt(String encryptString, int z){char[] codeChar = encryptString.toCharArray();char[] enCharArray;enCharArray = new char[codeChar.length];for(int i = 0; i < codeChar.length; i++){int x = codeChar[i];int enInt = encryptChar(x, z);char enChar = (char)enInt;enCharArray[i] = enChar;if(x == 32){enInt = 32;enChar = (char)enInt;enCharArray[i] = enChar;}}return enCharArray;}static char[] decrypt(String decryptString, int z){char[] deCodeChar = decryptString.toCharArray();char[] deCharArray;deCharArray = new char[deCodeChar.length];for(int i = 0; i < deCodeChar.length; i++){int x = deCodeChar[i];int deInt = decryptChar(x, z);char deChar = (char)deInt;deCharArray[i] = deChar;if(x == 32){deInt = 32;deChar = (char)deInt;deCharArray[i] = deChar;}}return deCharArray;}static int encryptChar(int x, int z){int y = 'A';int enInt = (x - y + z) % 26 + y;return enInt;}static int decryptChar(int x, int z){int y = 'A';int deInt = (x - y + 104 - z) % 26 + y;return deInt;}static int getRandom(){int encryptMethod = 0;while(encryptMethod == 0){Random encrypt = new Random();encryptMethod = encrypt.nextInt(96);}return encryptMethod;}}I keep getting these errors when i try to compile:EncryptionDecryption.java:32: unreported exception java.io.FileNotFoundException; must be caught or declared to be thrownScanner input = new Scanner(new File(\" \"));                ^EncryptionDecryption.java:38: unreported exception java.io.FileNotFoundException; must be caught or declared to be thrownPrintWriter work = new PrintWriter(\"EncryptedDocument.txt\");                   ^2 errors\nPlease using this api: PrintWriter.write.\nAnswer:", "response": "Please answer my code questions using the given API following this format: <<<api>>>: $API\n<<<code>>>: $CODE\n<<<explanation>>>: $EXPLANATION.\nQuestion: Why do I keep getting the \"must be caught or declared to be thrown\" error?: :                                This question is unlikely to help any future visitors; it is only relevant to a small geographic area, a specific moment in time,  or an extraordinarily narrow situation that is not generally applicable to the worldwide audience of the internet. For help making  this question more broadly applicable, visit the help center.                                                            Closed 11 years ago.Here is my codeimport java.io.*;import java.util.*;import java.util.Scanner;import java.io.PrintWriter;public class EncryptionDecryption {public static void main(String[] args) throws java.io.IOException{int z = getRandom();boolean luck = true;while(luck == true){String codeString = getString();System.out.println(codeString);char[] enCharArray = encrypt(codeString, z);String encryptedString = new String(enCharArray);System.out.println(encryptedString);char[] deCharArray = decrypt(encryptedString, z);String decryptedString = new String(deCharArray);System.out.println(decryptedString);putString(encryptedString);if(codeString.length() == 0)luck = false;}}static String getString(){Scanner input = new Scanner(new File(\" \"));String codeString = input.next();return codeString;}static void putString (String finalString){PrintWriter work = new PrintWriter(\"EncryptedDocument.txt\");work.print(finalString + \" \");work.close();}static char[] encrypt(String encryptString, int z){char[] codeChar = encryptString.toCharArray();char[] enCharArray;enCharArray = new char[codeChar.length];for(int i = 0; i < codeChar.length; i++){int x = codeChar[i];int enInt = encryptChar(x, z);char enChar = (char)enInt;enCharArray[i] = enChar;if(x == 32){enInt = 32;enChar = (char)enInt;enCharArray[i] = enChar;}}return enCharArray;}static char[] decrypt(String decryptString, int z){char[] deCodeChar = decryptString.toCharArray();char[] deCharArray;deCharArray = new char[deCodeChar.length];for(int i = 0; i < deCodeChar.length; i++){int x = deCodeChar[i];int deInt = decryptChar(x, z);char deChar = (char)deInt;deCharArray[i] = deChar;if(x == 32){deInt = 32;deChar = (char)deInt;deCharArray[i] = deChar;}}return deCharArray;}static int encryptChar(int x, int z){int y = 'A';int enInt = (x - y + z) % 26 + y;return enInt;}static int decryptChar(int x, int z){int y = 'A';int deInt = (x - y + 104 - z) % 26 + y;return deInt;}static int getRandom(){int encryptMethod = 0;while(encryptMethod == 0){Random encrypt = new Random();encryptMethod = encrypt.nextInt(96);}return encryptMethod;}}I keep getting these errors when i try to compile:EncryptionDecryption.java:32: unreported exception java.io.FileNotFoundException; must be caught or declared to be thrownScanner input = new Scanner(new File(\" \"));                ^EncryptionDecryption.java:38: unreported exception java.io.FileNotFoundException; must be caught or declared to be thrownPrintWriter work = new PrintWriter(\"EncryptedDocument.txt\");                   ^2 errors\nPlease using this api: PrintWriter.write.\nAnswer: The errors are due to the fact that the FileNotFoundException is not being caught. This exception is thrown when the file you are trying to open does not exist. In your case, you are trying to open a file with the name \" \" (a space character). You need to either provide a valid file name or handle the FileNotFoundException.\n\nHere is the corrected code:\n\n```java\nimport java.io.*;\nimport java.util.*;\nimport java.util.Scanner;\nimport java.io.PrintWriter;\n\npublic class EncryptionDecryption {\n    public static void main(String[] args) {\n        int z = getRandom();\n        boolean luck = true;\n        while(luck == true){\n            String codeString = getString();\n            System.out.println(codeString);\n            char[] enCharArray = encrypt(codeString, z);\n            String encryptedString = new String(enCharArray);\n            System.out.println(encryptedString);\n            char[] deCharArray = decrypt(encryptedString, z);\n            String decryptedString = new String(deCharArray);\n            System.out.println(decryptedString);\n            putString(encryptedString);\n            if(codeString.length() == 0)\n                luck = false;\n        }\n    }\n\n    static String getString(){\n        Scanner input = null;\n        try {\n            input = new Scanner(new File(\"input.txt\")); // replace with your file name\n        } catch (FileNotFoundException e) {\n            e.printStackTrace();\n        }\n        String codeString = input.next();\n        return codeString;\n    }\n\n    static void putString (String finalString){\n        PrintWriter work = null;\n        try {\n            work = new PrintWriter(\"EncryptedDocument.txt\");\n        } catch (FileNotFoundException e) {\n            e.printStackTrace();\n        }\n        work.print(finalString + \" \");\n        work.close();\n    }\n\n    static char[] encrypt(String encryptString, int z){\n        char[] codeChar = encryptString.toCharArray();\n        char[] enCharArray = new char[codeChar.length];\n        for(int i = 0; i < codeChar.length; i++){\n            int x = codeChar[i];\n            int enInt = encryptChar(x, z);\n            char enChar = (char)enInt;\n            enCharArray[i] = enChar;\n            if(x == 32){\n                enInt = 32;\n                enChar = (char)enInt;\n                enCharArray[i] = enChar;\n            }\n        }\n        return enCharArray;\n    }\n\n    static char[] decrypt(String decryptString, int z){\n        char[] deCodeChar = decryptString.toCharArray();\n        char[] deCharArray = new char[deCodeChar.length];\n        for(int i = 0; i < deCodeChar.length; i++){\n            int x = deCodeChar[i];\n            int deInt = decryptChar(x, z);\n            char deChar = (char)deInt;\n            deCharArray[i] = deChar;\n            if(x == 32){\n                deInt = 32;\n                deChar = (char)deInt;\n                deCharArray[i] = deChar;\n            }\n        }\n        return deCharArray;\n    }\n\n    static int encryptChar(int x, int z){\n        int y = 'A';\n        int enInt = (x - y + z) % 26 + y;\n        return enInt;\n    }\n\n    static int decryptChar(int x, int z){\n        int y = 'A';\n        int deInt = (x - y + 104 - z) % 26 + y;\n        return deInt;\n    }\n\n    static int getRandom(){\n        int encryptMethod = 0;\n        while(encryptMethod == 0){\n            Random encrypt = new Random();\n            encryptMethod = encrypt.nextInt(96);\n        }\n        return encryptMethod;\n    }\n}\n```\n\nIn the corrected code, I have added try-catch blocks to handle the FileNotFoundException. You"}