{"api": "InputStream.read", "prompt": "Please answer my code questions using the given API following this format: <<<api>>>: $API\n<<<code>>>: $CODE\n<<<explanation>>>: $EXPLANATION.\nQuestion: How to reproduce \"java.net.SocketException.Connection reset\"?: :I am trying to reproduce \"java.net.SocketException.Connection reset\" exception. Wanted to know if there is any program available which could help me simulate it. I tried following Server and client programs to see if I could simulate but I am not able to get any exception. I am using java8.Server Code-import java.io.BufferedReader;import java.io.IOException;import java.io.InputStreamReader;import java.net.ServerSocket;import java.net.Socket;import java.net.SocketException;import java.net.SocketTimeoutException;public class SimpleServerApp {    public static void main(String[] args) throws InterruptedException {        new Thread(new SimpleServer()).start();    }    static class SimpleServer implements Runnable {        @Override        public void run() {            ServerSocket serverSocket = null;            try {                serverSocket = new ServerSocket(3333);                serverSocket.setSoTimeout(0);                //serverSocket.                while (true) {                    try {                        Socket clientSocket = serverSocket.accept();                        BufferedReader inputReader = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));                        System.out.println(\"Client said :\"+ inputReader.readLine());                    } catch (SocketTimeoutException e) {                        e.printStackTrace();                    }                }            }catch (Exception e) {                e.printStackTrace();                System.out.println(\" EXCEPTION \" + e.getStackTrace());            }/*catch (IOException e1) {                e1.printStackTrace();            }*/ /*finally {                try {                    if (serverSocket != null) {                        serverSocket.close();                    }                } catch (IOException e) {                    e.printStackTrace();                }            }*/        }    }}Client Code - import java.io.IOException;import java.io.PrintWriter;import java.net.Socket;import java.net.SocketException;import java.net.UnknownHostException;public class SimpleClientApp {    public static void main(String[] args) {        new Thread(new SimpleClient()).start();    }    static class SimpleClient implements Runnable {        @Override        public void run() {            Socket socket = null;            try {                socket = new Socket(\"localhost\", 3333);                PrintWriter outWriter = new PrintWriter(socket.getOutputStream(), true);                System.out.println(\"Wait\");                Thread.sleep(20000);                //System.exit(0);                //throw new Exception(\"Random exception\");                //socket.close();                outWriter.println(\"Hello Mr. Server!\");            }catch (SocketException e) {                e.printStackTrace();            }catch (InterruptedException e) {                e.printStackTrace();            } catch (UnknownHostException e) {                e.printStackTrace();            } catch (IOException e) {                e.printStackTrace();            } catch (Exception e) {                // TODO Auto-generated catch block                e.printStackTrace();            } /*finally {                try {                    if (socket != null)                        socket.close();                } catch (IOException e) {                    e.printStackTrace();                }            }*/      }    }}Scenario 1. Start the server program locally.  Start the Client program locally.Close the client program abruptly (Ctrl C) - I just get output onServer program \"Client said :null\"Scenario 2.Start the Server program Locally.Start the client program locally.Client is connected to server, Then while client program is waiting close the server program abruptly. Still no exception.Can some tell me some way I could produce the connection reset exception, With working sample code.  \nPlease using this api: InputStream.read.\nAnswer:", "response": "Please answer my code questions using the given API following this format: <<<api>>>: $API\n<<<code>>>: $CODE\n<<<explanation>>>: $EXPLANATION.\nQuestion: How to reproduce \"java.net.SocketException.Connection reset\"?: :I am trying to reproduce \"java.net.SocketException.Connection reset\" exception. Wanted to know if there is any program available which could help me simulate it. I tried following Server and client programs to see if I could simulate but I am not able to get any exception. I am using java8.Server Code-import java.io.BufferedReader;import java.io.IOException;import java.io.InputStreamReader;import java.net.ServerSocket;import java.net.Socket;import java.net.SocketException;import java.net.SocketTimeoutException;public class SimpleServerApp {    public static void main(String[] args) throws InterruptedException {        new Thread(new SimpleServer()).start();    }    static class SimpleServer implements Runnable {        @Override        public void run() {            ServerSocket serverSocket = null;            try {                serverSocket = new ServerSocket(3333);                serverSocket.setSoTimeout(0);                //serverSocket.                while (true) {                    try {                        Socket clientSocket = serverSocket.accept();                        BufferedReader inputReader = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));                        System.out.println(\"Client said :\"+ inputReader.readLine());                    } catch (SocketTimeoutException e) {                        e.printStackTrace();                    }                }            }catch (Exception e) {                e.printStackTrace();                System.out.println(\" EXCEPTION \" + e.getStackTrace());            }/*catch (IOException e1) {                e1.printStackTrace();            }*/ /*finally {                try {                    if (serverSocket != null) {                        serverSocket.close();                    }                } catch (IOException e) {                    e.printStackTrace();                }            }*/        }    }}Client Code - import java.io.IOException;import java.io.PrintWriter;import java.net.Socket;import java.net.SocketException;import java.net.UnknownHostException;public class SimpleClientApp {    public static void main(String[] args) {        new Thread(new SimpleClient()).start();    }    static class SimpleClient implements Runnable {        @Override        public void run() {            Socket socket = null;            try {                socket = new Socket(\"localhost\", 3333);                PrintWriter outWriter = new PrintWriter(socket.getOutputStream(), true);                System.out.println(\"Wait\");                Thread.sleep(20000);                //System.exit(0);                //throw new Exception(\"Random exception\");                //socket.close();                outWriter.println(\"Hello Mr. Server!\");            }catch (SocketException e) {                e.printStackTrace();            }catch (InterruptedException e) {                e.printStackTrace();            } catch (UnknownHostException e) {                e.printStackTrace();            } catch (IOException e) {                e.printStackTrace();            } catch (Exception e) {                // TODO Auto-generated catch block                e.printStackTrace();            } /*finally {                try {                    if (socket != null)                        socket.close();                } catch (IOException e) {                    e.printStackTrace();                }            }*/      }    }}Scenario 1. Start the server program locally.  Start the Client program locally.Close the client program abruptly (Ctrl C) - I just get output onServer program \"Client said :null\"Scenario 2.Start the Server program Locally.Start the client program locally.Client is connected to server, Then while client program is waiting close the server program abruptly. Still no exception.Can some tell me some way I could produce the connection reset exception, With working sample code.  \nPlease using this api: InputStream.read.\nAnswer: <<<api>>>: InputStream.read\n<<<code>>>: int read() throws IOException\n<<<explanation>>>: Reads the next byte of data from the input stream. The value byte is returned as an int in the range 0 to 255. If no byte is available because the end of the stream has been reached, the value -1 is returned. This method blocks until input data is available, the end of the stream is detected, or an exception is thrown.\n\nA: I'm not sure what you mean by \"simulate\" but here's a simple example of how to simulate a connection reset:\nimport java.io.IOException;\nimport java.net.ServerSocket;\nimport java.net.Socket;\n\npublic class Server {\n\n    public static void main(String[] args) throws IOException {\n        ServerSocket serverSocket = new ServerSocket(3333);\n        Socket socket = serverSocket.accept();\n        socket.close();\n    }\n}\n\nimport java.io.IOException;\nimport java.net.Socket;\n\npublic class Client {\n\n    public static void main(String[] args) throws IOException {\n        Socket socket = new Socket(\"localhost\", 3333);\n        socket.close();\n    }\n}\n\n"}